### ISSUE TITLE
the ability to switch player tracking

### ISSUE THREAD

**Issue by LoneWolfGmer** [Anuken/Mindustry-Suggestions#2916]
### Describe the content or mechanics you are proposing.

Like in how the phone version. They got it so that the player character snaps to your current camera look point.

I'm thinking what about adding the ability to switch between that and normal view mode.
I find it annoying that I'm building stuff and moved around then get snapped back to the bot upon pausing.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It could help with those doing the game in solo so that they can build stuff for effectively and help those used to gaming on the phone version

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
